services:
  mariadb:
    image: mariadb:11.4
    container_name: crud_hr_mariadb
    restart: unless-stopped
    env_file:
      - ./.tmp/local-mariadb.env
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - crud_hr_mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 30

volumes:
  crud_hr_mariadb_data:
