# Generated by Django 6.0.3 on 2026-03-29 16:43

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='annual_leave_allowance',
            field=models.PositiveIntegerField(default=18),
        ),
        migrations.CreateModel(
            name='EmployeeSanction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sanction_type', models.CharField(choices=[('WARNING', 'Warning'), ('BLAME', 'Blame')], max_length=20)),
                ('subject', models.CharField(max_length=150)),
                ('details', models.TextField()),
                ('issued_on', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanctions', to='employees.employee')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_sanctions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_on', '-created_at'],
                'indexes': [models.Index(fields=['employee', 'issued_on'], name='employees_e_employe_04b374_idx'), models.Index(fields=['sanction_type'], name='employees_e_sanctio_0914cf_idx')],
            },
        ),
        migrations.CreateModel(
            name='HolidayRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('ANNUAL', 'Annual Leave'), ('SICK', 'Sick Leave'), ('UNPAID', 'Unpaid Leave'), ('PERSONAL', 'Personal Leave')], default='ANNUAL', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('handover_notes', models.TextField(blank=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=120)),
                ('hr_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=12)),
                ('hr_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('ceo_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=12)),
                ('ceo_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ceo_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ceo_reviewed_holiday_requests', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holiday_requests', to='employees.employee')),
                ('hr_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_reviewed_holiday_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee', 'created_at'], name='employees_h_employe_7015d4_idx'), models.Index(fields=['hr_status', 'ceo_status'], name='employees_h_hr_stat_a7b0f0_idx'), models.Index(fields=['start_date', 'end_date'], name='employees_h_start_d_430136_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkedHourLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('scheduled_hours', models.DecimalField(decimal_places=2, default=Decimal('8.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('worked_hours', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worked_hour_logs', to='employees.employee')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_worked_hours', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-work_date', '-created_at'],
                'indexes': [models.Index(fields=['employee', 'work_date'], name='employees_w_employe_90a43b_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'work_date'), name='unique_employee_work_date')],
            },
        ),
    ]
